//>>built
require({cache:{"JBrowse/Plugin":function(){define("JBrowse/Plugin",["dojo/_base/declare","JBrowse/Component"],function(f,b){return f(b,{constructor:function(b){this.name=b.name;this.cssLoaded=b.cssLoaded;this._finalizeConfig(b.config)},_defaultConfig:function(){return{baseUrl:"/plugins/"+this.name}}})})},"RegexSequenceSearch/View/SearchSeqDialog":function(){define("dojo/_base/declare,dojo/dom-construct,dojo/aspect,dijit/focus,dijit/form/Button,dijit/form/RadioButton,dijit/form/CheckBox,dijit/form/TextBox,JBrowse/View/Dialog/WithActionBar".split(","),
function(f,b,o,j,n,l,g,h,a){return f(a,{constructor:function(){var k=this;o.after(this,"hide",function(){j.curNode&&j.curNode.blur();setTimeout(function(){k.destroyRecursive()},500)})},_dialogContent:function(){function k(c,a){var k=b.create("label",{},a),e=(new l(c)).placeAt(k);b.create("span",{innerHTML:c.label},k);return e}var c=this.content={},a=b.create("div",{className:"search-dialog"});b.create("div",{className:"search-dialog intro",innerHTML:"This tool creates tracks showing regions of the reference sequence (or its translations) that match a given DNA or amino acid sequence."},
a);var e=b.create("div",{className:"section"},a);b.create("span",{className:"header",innerHTML:"Search for"},e);var d=b.create("div",{className:"translateContainer"},e);k({name:"translate",value:"no",label:"DNA",checked:!0},d);c.translate=k({name:"translate",value:"yes",label:"AA"},d);c.searchBox=(new h({})).placeAt(e);e=b.create("div",{className:"section"},a);d=b.create("div",{className:"checkboxdiv"},e);c.caseIgnore=new g({label:"Ignore case",id:"search_ignore_case",checked:!0});d.appendChild(c.caseIgnore.domNode);
b.create("label",{"for":"search_ignore_case",innerHTML:"Ignore Case"},d);e=b.create("div",{className:"checkboxdiv"},e);c.regex=(new g({label:"Treat as regular expression",id:"search_as_regex"})).placeAt(e);b.create("label",{"for":"search_as_regex",innerHTML:"Treat as regular expression"},e);e=b.create("div",{className:"section"},a);b.create("span",{className:"header",innerHTML:"Search strands"},e);d=b.create("div",{className:"checkboxdiv"});c.fwdStrand=new g({id:"search_fwdstrand",checked:!0});var i=
b.create("div",{className:"checkboxdiv"});c.revStrand=new g({id:"search_revstrand",checked:!0});d.appendChild(c.fwdStrand.domNode);b.create("label",{"for":"search_fwdstrand",innerHTML:"Forward"},d);i.appendChild(c.revStrand.domNode);b.create("label",{"for":"search_revstrand",innerHTML:"Reverse"},i);e.appendChild(d);e.appendChild(i);return a},_getSearchParams:function(){var a=this.content;return{expr:a.searchBox.get("value"),regex:a.regex.checked,caseIgnore:a.caseIgnore.checked,translate:a.translate.checked,
fwdStrand:a.fwdStrand.checked,revStrand:a.revStrand.checked,maxLen:100}},_fillActionBar:function(a){var c=this;(new n({label:"Search",iconClass:"dijitIconBookmark",onClick:function(){var a=c._getSearchParams();c.callback(a);c.hide()}})).placeAt(a);(new n({label:"Cancel",iconClass:"dijitIconDelete",onClick:function(){c.callback(!1);c.hide()}})).placeAt(a)},show:function(a){this.callback=a||function(){};this.set("title","Add sequence search track");this.set("content",this._dialogContent());this.inherited(arguments);
j.focus(this.closeButtonNode)}})})},"RegexSequenceSearch/Store/SeqFeature/RegexSearch":function(){define("dojo/_base/declare,dojo/_base/array,dojo/_base/lang,JBrowse/Store/SeqFeature,JBrowse/Model/SimpleFeature,JBrowse/Errors,JBrowse/Util,JBrowse/CodonTable".split(","),function(f,b,o,j,n,l,g,h){return f(j,{constructor:function(a){this.searchParams=a.searchParams},_defaultConfig:function(){return g.deepUpdate(dojo.clone(this.inherited(arguments)),{regionSizeLimit:2E5})},getFeatures:function(a,b,c,
g){var e=o.mixin({orig:{start:a.start,end:a.end}},this.searchParams,a.searchParams);if(a.end-a.start>this.config.regionSizeLimit)throw new l.DataOverflow("Region too large to search");var d=this;this.browser.getStore("refseqs",function(i){i?i.getReferenceSequence(a,function(i){d.doSearch(a,i,e,b);c()},g):c()})},doSearch:function(a,k,c,h){var e=RegExp(c.regex?c.expr:this.escapeString(c.expr),c.caseIgnore?"gi":"g"),d=[];c.fwdStrand&&d.push([k,1]);c.revStrand&&d.push([g.revcom(k),-1]);b.forEach(d,function(b){if(c.translate)for(var d=
0;3>d;d++)this._searchSequence(a,b[0],e,b[1],h,!0,d);else this._searchSequence(a,b[0],e,b[1],h)},this)},_searchSequence:function(a,b,c,g,e,d,i){d&&(b=this.translateSequence(b,i));for(var i=i||0,d=d?3:1,h=a.start,a=a.end,m;null!==(m=c.exec(b))&&m.length;){c.lastIndex=m.index+1;var f=m[0],j=0<g?h+i+d*m.index:a-i-d*(m.index+f.length),l=0<g?h+i+d*(m.index+f.length):a-i-d*m.index,f=new n({data:{start:j,end:l,searchMatch:f,strand:g},id:[j,l,f].join()});e(f)}},translateSequence:function(a,b){for(var c=a.slice(b),
c=c.slice(0,3*Math.floor(c.length/3)),g="",e=0;e<c.length;e+=3)var d=c.slice(e,e+3),g=g+h[d];return g},escapeString:function(a){return(a+"").replace(/([.?*+^$[\]\\(){}|-])/g,"\\$1")}})})}}});
define("RegexSequenceSearch/main","dojo/_base/declare,dojo/_base/lang,dojo/Deferred,dijit/MenuItem,JBrowse/Plugin,./View/SearchSeqDialog".split(","),function(f,b,o,j,n,l){return f(n,{constructor:function(){this._searchTrackCount=0;this.browser.afterMilestone("initView",function(){this.browser.addGlobalMenuItem("file",new j({label:"Add sequence search track",iconClass:"dijitIconBookmark",onClick:b.hitch(this,"createSearchTrack")}))},this)},createSearchTrack:function(){var b=this;(new l).show(function(h){if(h){var a=
{browser:b.browser,refSeq:b.browser.refSeq,type:"RegexSequenceSearch/Store/SeqFeature/RegexSearch",searchParams:h},f=b.browser.addStoreConfig(void 0,a);a.name=f;h={type:"JBrowse/View/Track/CanvasFeatures",label:"search_track_"+b._searchTrackCount++,key:"Search reference sequence for '"+h.expr+"'",metadata:{category:"Local tracks",Description:"Contains all matches of the text string/regular expression '"+a.searchExpr+"'"},store:f};b.browser.publish("/jbrowse/v1/v/tracks/new",[h]);b.browser.publish("/jbrowse/v1/v/tracks/show",
[h])}})}})});