//>>built
require({cache:{"dojo/fx/easing":function(){define("dojo/fx/easing",["../_base/lang"],function(h){var d={linear:function(a){return a},quadIn:function(a){return Math.pow(a,2)},quadOut:function(a){return-1*a*(a-2)},quadInOut:function(a){a*=2;return 1>a?Math.pow(a,2)/2:-1*(--a*(a-2)-1)/2},cubicIn:function(a){return Math.pow(a,3)},cubicOut:function(a){return Math.pow(a-1,3)+1},cubicInOut:function(a){a*=2;return 1>a?Math.pow(a,3)/2:(Math.pow(a-2,3)+2)/2},quartIn:function(a){return Math.pow(a,4)},quartOut:function(a){return-1*
(Math.pow(a-1,4)-1)},quartInOut:function(a){a*=2;return 1>a?Math.pow(a,4)/2:-0.5*(Math.pow(a-2,4)-2)},quintIn:function(a){return Math.pow(a,5)},quintOut:function(a){return Math.pow(a-1,5)+1},quintInOut:function(a){a*=2;return 1>a?Math.pow(a,5)/2:(Math.pow(a-2,5)+2)/2},sineIn:function(a){return-1*Math.cos(a*(Math.PI/2))+1},sineOut:function(a){return Math.sin(a*(Math.PI/2))},sineInOut:function(a){return-1*(Math.cos(Math.PI*a)-1)/2},expoIn:function(a){return 0==a?0:Math.pow(2,10*(a-1))},expoOut:function(a){return 1==
a?1:-1*Math.pow(2,-10*a)+1},expoInOut:function(a){if(0==a)return 0;if(1==a)return 1;a*=2;if(1>a)return Math.pow(2,10*(a-1))/2;--a;return(-1*Math.pow(2,-10*a)+2)/2},circIn:function(a){return-1*(Math.sqrt(1-Math.pow(a,2))-1)},circOut:function(a){return Math.sqrt(1-Math.pow(a-1,2))},circInOut:function(a){a*=2;return 1>a?-0.5*(Math.sqrt(1-Math.pow(a,2))-1):0.5*(Math.sqrt(1-Math.pow(a-2,2))+1)},backIn:function(a){return Math.pow(a,2)*(2.70158*a-1.70158)},backOut:function(a){a-=1;return Math.pow(a,2)*(2.70158*
a+1.70158)+1},backInOut:function(a){a*=2;if(1>a)return Math.pow(a,2)*(3.5949095*a-2.5949095)/2;a-=2;return(Math.pow(a,2)*(3.5949095*a+2.5949095)+2)/2},elasticIn:function(a){if(0==a||1==a)return a;a-=1;return-1*Math.pow(2,10*a)*Math.sin((a-0.075)*2*Math.PI/0.3)},elasticOut:function(a){return 0==a||1==a?a:Math.pow(2,-10*a)*Math.sin((a-0.075)*2*Math.PI/0.3)+1},elasticInOut:function(a){if(0==a)return 0;a*=2;if(2==a)return 1;var d=0.3*1.5,g=d/4;if(1>a)return a-=1,-0.5*Math.pow(2,10*a)*Math.sin((a-g)*2*
Math.PI/d);a-=1;return 0.5*Math.pow(2,-10*a)*Math.sin((a-g)*2*Math.PI/d)+1},bounceIn:function(a){return 1-d.bounceOut(1-a)},bounceOut:function(a){return a=a<1/2.75?7.5625*Math.pow(a,2):a<2/2.75?7.5625*Math.pow(a-1.5/2.75,2)+0.75:a<2.5/2.75?7.5625*Math.pow(a-2.25/2.75,2)+0.9375:7.5625*Math.pow(a-2.625/2.75,2)+0.984375},bounceInOut:function(a){return 0.5>a?d.bounceIn(2*a)/2:d.bounceOut(2*a-1)/2+0.5}};h.setObject("dojo.fx.easing",d);return d})}}});
define("JBrowse/View/TrackList/Simple","dojo/_base/declare,dojo/_base/array,dojo/_base/event,dojo/keys,dojo/on,dojo/dom-construct,dojo/dom-class,dijit/layout/ContentPane,dojo/dnd/Source,dojo/fx/easing,dijit/form/TextBox,./_TextFilterMixin".split(","),function(h,d,a,i,g,n,o,j,k,l,p,m){return h("JBrowse.View.TrackList.Simple",m,{constructor:function(a){this.browser=a.browser;this.createTrackList(a.browser.container);this.inactiveTrackNodes={};this.trackListWidget.insertNodes(!1,a.trackConfigs);this.browser.subscribe("/dnd/drop",
dojo.hitch(this,function(a,b,c,d){if(d===this.trackListWidget&&(a=dojo.filter(dojo.map(b,function(a){return a.track&&a.track.config}),function(a){return a}),a.length))this.dndDrop=!0,this.browser.publish("/jbrowse/v1/v/tracks/hide",a),this.dndDrop=!1}));this.browser.subscribe("/jbrowse/v1/c/tracks/show",dojo.hitch(this,"setTracksActive"));this.browser.subscribe("/jbrowse/v1/c/tracks/hide",dojo.hitch(this,"setTracksInactive"));this.browser.subscribe("/jbrowse/v1/c/tracks/new",dojo.hitch(this,"addTracks"));
this.browser.subscribe("/jbrowse/v1/c/tracks/replace",dojo.hitch(this,"replaceTracks"));this.browser.subscribe("/jbrowse/v1/c/tracks/delete",dojo.hitch(this,"deleteTracks"))},addTracks:function(a){this.trackListWidget.insertNodes(!1,a);this._blinkTracks(a)},replaceTracks:function(a){d.forEach(a,function(a){var b=this.inactiveTrackNodes[a.label];b&&(delete this.inactiveTrackNodes[a.label],this.trackListWidget.delItem(b.id),b.parentNode&&b.parentNode.removeChild(b),this.trackListWidget.insertNodes(!1,
[a],!1,b.previousSibling))},this)},createTrackList:function(a){a=dojo.create("div",{id:"trackPane",className:"jbrowseSimpleTrackSelector",style:{width:"12em"}},a);new j({region:"left",splitter:!0},a);a=this.div=this.containerNode=dojo.create("div",{id:"tracksAvail",className:"container handles",style:{width:"100%",height:"100%",overflowX:"hidden",overflowY:"auto"},innerHTML:"<h2>Available Tracks</h2>"},a);this._makeTextFilterNodes(a);this._updateTextFilterControl();this.trackListWidget=new k(a,{accept:["track"],
withHandles:!1,creator:dojo.hitch(this,function(a,b){var c=a.key||a.name||a.label,c=dojo.create("div",{className:"tracklist-label",title:c+" (drag or double-click to activate)",innerHTML:c});if("avatar"!=b){g(c,"dblclick",dojo.hitch(this,function(){this.browser.publish("/jbrowse/v1/v/tracks/show",[a])}));var d=dojo.create("div",{className:"tracklist-container"});d.appendChild(c);c=d;c.id=dojo.dnd.getUniqueId();this.inactiveTrackNodes[a.label]=c}return{node:c,data:a,type:["track"]}})});this.trackListWidget.onMouseDown=
dojo.hitch(this,"onMouseDown");this.trackListWidget.onMouseUp=dojo.hitch(this,"onMouseUp");g(document,"keydown",dojo.hitch(this,"onKeyDown"));return a},onKeyDown:function(a){switch(a.keyCode){case i.ESCAPE:this.trackListWidget.selectNone()}},onMouseDown:function(a){var e=this.trackListWidget;if(!e.mouseDown&&e._legalMouseDown(a))e.mouseDown=!0,e._lastX=a.pageX,e._lastY=a.pageY,this._onMouseDown(e.current,a)},_onMouseDown:function(b,e){if(b){var f=this.trackListWidget;if(!e.ctrlKey&&!e.shiftKey&&(f.simpleSelection=
!0,!this._isSelected(b)))f.selectNone(),f.simpleSelection=!1;if(e.shiftKey&&this.anchor){var c=0,f=f.getAllNodes();this._select(b);if(b!=this.anchor){for(;c<f.length&&!(f[c]==this.anchor||f[c]==b);c++);for(c++;c<f.length&&!(f[c]==this.anchor||f[c]==b);c++)this._select(f[c])}}else e.ctrlKey?this._toggle(b):this._select(b),this.anchor=b;a.stop(e)}},onMouseUp:function(a){var e=this.trackListWidget;if(e.mouseDown)e.mouseDown=!1,this._onMouseUp(a)},_onMouseUp:function(){var a=this.trackListWidget;a.simpleSelection&&
a.current&&(a.selectNone(),this._select(a.current))},_isSelected:function(a){return this.trackListWidget.selection[a.id]},_select:function(a){this.trackListWidget.selection[a.id]=1;this.trackListWidget._addItemClass(a,"Selected")},_deselect:function(a){delete this.trackListWidget.selection[a.id];this.trackListWidget._removeItemClass(a,"Selected")},_toggle:function(a){this.trackListWidget.selection[a.id]?this._deselect(a):this._select(a)},setTracksActive:function(a){this.deleteTracks(a)},deleteTracks:function(a){d.forEach(a||
[],function(a){var b=this.inactiveTrackNodes[a.label];b&&(delete this.inactiveTrackNodes[a.label],b.parentNode&&b.parentNode.removeChild(b),this.trackListWidget.delItem(b.id))},this)},setTracksInactive:function(a){this.dndDrop||(this.trackListWidget.insertNodes(!1,a),this._blinkTracks(a))},_blinkTracks:function(a){this.trackListWidget.node.scrollTop=this.trackListWidget.node.scrollHeight;d.forEach(a,function(a){var b=this.inactiveTrackNodes[a.label].firstChild;b&&dojo.animateProperty({node:b,duration:400,
properties:{backgroundColor:{start:"#DEDEDE",end:"#FFDE2B"}},easing:l.sine,repeat:2,onEnd:function(){b.style.backgroundColor=null}}).play()},this)},show:function(){},hide:function(){},toggle:function(){}})});